### ISSUE TITLE
runtime crash "** (KeyError) key :tags not found in: nil" -- commit 957a96b419ef728a6f51162e6eb123a6e73e570f(headrev)

### ISSUE THREAD

**Issue by mazz** [algora-io/tv#126]
On my dev machine, If I'm not logged-in, I'm getting a crash when I open the url `http://localhost:4000/algora/1`(lib/algora_web/live/video_live.ex:661) when the runtime tries to access `current_user.tags` in this context:

```
    socket =
      socket
      |> assign(
        channel: channel,
        owns_channel?: current_user && Library.owns_channel?(current_user, channel),
        videos_count: Enum.count(videos),
        video: video,
        subtitles: subtitles,
        tabs: tabs,
        tags: current_user.tags, ################## HERE #####################
        # TODO: reenable once fully implemented
        # associated segments need to be removed from db & vectorstore
        can_edit: false,
        subscribed?: subscribed?(current_user, video),
        transcript_form: to_form(transcript_changeset, as: :data),
        chat_form: to_form(Chat.change_message(%Chat.Message{})),
        video_thumbnails: video_thumbnails,
        has_many_thumbnails?: length(video_thumbnails) > 1,
        thumbnail_form: to_form(Library.Video.change_thumbnail(video, video.thumbnail_url))
      )
      |> stream(:videos, videos)
      |> stream(:messages, Chat.list_messages(video))
      |> stream(:presences, Presence.list_online_users(channel_handle))
```

trace:

```
[error] #PID<0.844.0> running Phoenix.Endpoint.SyncCodeReloadPlug (connection #PID<0.819.0>, stream id 6) terminated
Server: localhost:4000 (http)
Request: GET /algora/1
** (exit) an exception was raised:
    ** (KeyError) key :tags not found in: nil

If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
        (algora 0.1.0) lib/algora_web/live/video_live.ex:661: AlgoraWeb.VideoLive.mount/3
        (phoenix_live_view 0.20.12) lib/phoenix_live_view/utils.ex:354: anonymous fn/6 in Phoenix.LiveView.Utils.maybe_call_live_view_mount!/5
        (telemetry 1.3.0) /Volumes/Untitled/Users/Shared/src/phx/sandbox/tv/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
        (phoenix_live_view 0.20.12) lib/phoenix_live_view/static.ex:281: Phoenix.LiveView.Static.call_mount_and_handle_params!/5
        (phoenix_live_view 0.20.12) lib/phoenix_live_view/static.ex:116: Phoenix.LiveView.Static.render/3
        (phoenix_live_view 0.20.12) lib/phoenix_live_view/controller.ex:39: Phoenix.LiveView.Controller.live_render/3
        (phoenix 1.7.11) lib/phoenix/router.ex:484: Phoenix.Router.__call__/5
        (algora 0.1.0) lib/algora_web/endpoint.ex:1: AlgoraWeb.Endpoint.plug_builder_call/2
        (algora 0.1.0) deps/plug/lib/plug/debugger.ex:136: AlgoraWeb.Endpoint."call (overridable 3)"/2
        (algora 0.1.0) lib/algora_web/endpoint.ex:1: AlgoraWeb.Endpoint.call/2
        (phoenix 1.7.11) lib/phoenix/endpoint/sync_code_reload_plug.ex:22: Phoenix.Endpoint.SyncCodeReloadPlug.do_call/4
        (plug_cowboy 2.7.2) lib/plug/cowboy/handler.ex:11: Plug.Cowboy.Handler.init/2
        (cowboy 2.12.0) /Volumes/Untitled/Users/Shared/src/phx/sandbox/tv/deps/cowboy/src/cowboy_handler.erl:37: :cowboy_handler.execute/2
        (cowboy 2.12.0) /Volumes/Untitled/Users/Shared/src/phx/sandbox/tv/deps/cowboy/src/cowboy_stream_h.erl:306: :cowboy_stream_h.execute/3
        (cowboy 2.12.0) /Volumes/Untitled/Users/Shared/src/phx/sandbox/tv/deps/cowboy/src/cowboy_stream_h.erl:295: :cowboy_stream_h.request_process/3
        (stdlib 6.1) proc_lib.erl:329: :proc_lib.init_p_do_apply/3
```

**Comment by zcesur** [comment]
I had pushed a fix for this a few mins ago e7f7ab7, feel free to reopen if not resolved
